import pygame
from os import path

# Função para carregar todos os assets de uma vez
def load_assets(img_dir):
    assets = {}
    assets['PLAYER_FIRE'] = pygame.image.load(path.join(img_dir, 'Fireboy.png')).convert_alpha()
    assets['PLAYER_WATER'] = pygame.image.load(path.join(img_dir, 'watergirl.png')).convert_alpha()
    assets['BLOCK_IMG'] = pygame.image.load(path.join(img_dir, 'pedra.jpg')).convert()
    assets['BACKGROUND_IMG'] = pygame.image.load(path.join(img_dir, 'Background.png')).convert()
    assets['TILE_CENTER'] = pygame.image.load(path.join(img_dir, 'Tile_12.png')).convert()
    assets['TILE_TOP'] = pygame.image.load(path.join(img_dir, 'Tile_02.png')).convert()
    assets['TILE_BOTTOM'] = pygame.image.load(path.join(img_dir, 'Tile_05.png')).convert()
    assets['TILE_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_11.png')).convert()
    assets['TILE_TOP_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_01.png')).convert()
    assets['TILE_TOP_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_03.png')).convert()
    assets['TILE_EDGE_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_48.png')).convert()
    assets['TILE_EDGE_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_47.png')).convert()
    assets['TILE_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_14.png')).convert()
    assets['TILE_BOTTOM_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_21.png')).convert()
    assets['TILE_BOTTOM_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_23.png')).convert()
    assets['TILE_POINT_UP_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_24.png')).convert()
    assets['TILE_POINT_UP_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_57.png')).convert()
    assets['TILE_POINT_DOWN_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_06.png')).convert()
    assets['TILE_POINT_DOWN_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_04.png')).convert()
    assets['TILE_POINT_UP_LEFT_DOWN_RIGHT'] = pygame.image.load(path.join(img_dir, 'Tile_19.png')).convert()
    assets['TILE_POINT_UP_RIGHT_DOWN_LEFT'] = pygame.image.load(path.join(img_dir, 'Tile_29.png')).convert()
    assets['FIRE_PORTAL'] = pygame.image.load(path.join(img_dir, 'door1.png')).convert_alpha()
    assets['FIRE_PORTAL2'] = pygame.image.load(path.join(img_dir, 'door2.png')).convert_alpha()
    assets['WATER_PORTAL'] = pygame.image.load(path.join(img_dir, 'door3.png')).convert_alpha()
    assets['WATER_PORTAL2'] = pygame.image.load(path.join(img_dir, 'door4.png')).convert_alpha()
    assets['DIAMANTE_FIRE'] = pygame.image.load(path.join(img_dir, '1.png')).convert_alpha()
    assets['DIAMANTE_WATER'] = pygame.image.load(path.join(img_dir, '8.png')).convert_alpha()

    # Carregar as imagens de animação de fogo
    fireanimation_frames = []
    for i in range(0, 48):
        frame_path = path.join(img_dir, f'flame_{i}.png')  # Ajustado para flame_0.png até flame_48.png
        frame = pygame.image.load(frame_path).convert_alpha()
        frame = pygame.transform.scale(frame, (25, 25))
        fireanimation_frames.append(frame)
    assets['FIRE_ANIMATION'] = fireanimation_frames

    # Carregar as imagens de animação de água
    wateranimation_frames = []
    for i in range(0, 48):
        frame_path = path.join(img_dir, f'water_{i}.png')  # Ajustado para water_0.png até water_48.png
        frame = pygame.image.load(frame_path).convert_alpha()
        frame = pygame.transform.scale(frame, (25, 25))
        wateranimation_frames.append(frame)
    assets['WATER_ANIMATION'] = wateranimation_frames

    return assets

# Define os tipos de tiles
BLOCK = 0
EMPTY = -1

# Define o mapa com os tipos de tiles
MAP = [
    
    ['TILE_POINT_DOWN_LEFT', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_POINT_DOWN_RIGHT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'WATER_ANIMATION', "PLAYER_WATER", EMPTY, EMPTY, 'WATER_PORTAL', EMPTY, EMPTY, "DIAMANTE_WATER", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', 'FIRE_ANIMATION', "PLAYER_FIRE", EMPTY, EMPTY, 'FIRE_PORTAL', EMPTY, EMPTY, "DIAMANTE_FIRE", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT'],
]

MAP2 = [
    
    ['TILE_POINT_DOWN_LEFT', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_POINT_DOWN_RIGHT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'WATER_ANIMATION', "PLAYER_WATER", EMPTY, EMPTY, 'WATER_PORTAL', EMPTY, EMPTY, "DIAMANTE_WATER", "DIAMANTE_WATER", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', 'FIRE_ANIMATION', "PLAYER_FIRE", EMPTY, EMPTY, 'FIRE_PORTAL', EMPTY, EMPTY, "DIAMANTE_FIRE", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT'],
]

MAP3 = [
    
    ['TILE_POINT_DOWN_LEFT', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_POINT_DOWN_RIGHT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'WATER_ANIMATION', "PLAYER_WATER", EMPTY, EMPTY, 'WATER_PORTAL', EMPTY, EMPTY, "DIAMANTE_WATER", "DIAMANTE_WATER", "DIAMANTE_WATER", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', 'FIRE_ANIMATION', "PLAYER_FIRE", EMPTY, EMPTY, 'FIRE_PORTAL', EMPTY, EMPTY, "DIAMANTE_FIRE", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT'],
]

MAP4 = [
    
    ['TILE_POINT_DOWN_LEFT', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_POINT_DOWN_RIGHT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'WATER_ANIMATION', "PLAYER_WATER", EMPTY, EMPTY, 'WATER_PORTAL', EMPTY, "DIAMANTE_WATER", "DIAMANTE_WATER", "DIAMANTE_WATER", "DIAMANTE_WATER", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', 'FIRE_ANIMATION', "PLAYER_FIRE", EMPTY, EMPTY, 'FIRE_PORTAL', EMPTY, EMPTY, "DIAMANTE_FIRE", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT'],
]

MAP5 = [
    
    ['TILE_POINT_DOWN_LEFT', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_BOTTOM', 'TILE_POINT_DOWN_RIGHT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', 'TILE_CENTER', EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_CENTER', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT', 'TILE_CENTER', 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP_RIGHT', EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'WATER_ANIMATION', "PLAYER_WATER", EMPTY, EMPTY, 'WATER_PORTAL', EMPTY, EMPTY, "DIAMANTE_WATER", "DIAMANTE_WATER", "DIAMANTE_WATER", "DIAMANTE_WATER", "DIAMANTE_WATER", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, 'TILE_LEFT'],
    ['TILE_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_TOP_LEFT', 'TILE_POINT_UP_LEFT', 'TILE_LEFT'],
    ['TILE_RIGHT', 'FIRE_ANIMATION', "PLAYER_FIRE", EMPTY, EMPTY, 'FIRE_PORTAL', EMPTY, EMPTY, "DIAMANTE_FIRE", EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 'TILE_LEFT', 'TILE_CENTER', 'TILE_LEFT'],
    ['TILE_POINT_UP_RIGHT', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_TOP', 'TILE_POINT_UP_LEFT'],
]

def map_tiles(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    mapped_matrix = [[EMPTY for _ in range(cols)] for _ in range(rows)]

    def has_tile(x, y):
        return 0 <= x < rows and 0 <= y < cols and matrix[x][y] == 1

    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == 1:  # There's a tile here
                # Check neighbors
                top = has_tile(i - 1, j)
                bottom = has_tile(i + 1, j)
                left = has_tile(i, j - 1)
                right = has_tile(i, j + 1)
                top_left = has_tile(i - 1, j - 1)
                top_right = has_tile(i - 1, j + 1)
                bottom_left = has_tile(i + 1, j - 1)
                bottom_right = has_tile(i + 1, j + 1)

                # Determine tile type
                if top and bottom and left and right:
                    mapped_matrix[i][j] = 'TILE_CENTER'
                elif top and left and not bottom and not right:
                    mapped_matrix[i][j] = 'TILE_BOTTOM_RIGHT'
                elif top and right and not bottom and not left:
                    mapped_matrix[i][j] = 'TILE_BOTTOM_LEFT'
                elif bottom and left and not top and not right:
                    mapped_matrix[i][j] = 'TILE_TOP_RIGHT'
                elif bottom and right and not top and not left:
                    mapped_matrix[i][j] = 'TILE_TOP_LEFT'
                elif top and not bottom and not left and not right:
                    mapped_matrix[i][j] = 'TILE_BOTTOM'
                elif bottom and not top and not left and not right:
                    mapped_matrix[i][j] = 'TILE_TOP'
                elif left and not top and not bottom and not right:
                    mapped_matrix[i][j] = 'TILE_RIGHT'
                elif right and not top and not bottom and not left:
                    mapped_matrix[i][j] = 'TILE_LEFT'
                elif top and bottom and left and not right:
                    mapped_matrix[i][j] = 'TILE_EDGE_LEFT'
                elif top and bottom and right and not left:
                    mapped_matrix[i][j] = 'TILE_EDGE_RIGHT'
                elif top and left and bottom and right:
                    mapped_matrix[i][j] = 'TILE_POINT_UP_LEFT_DOWN_RIGHT'
                elif top and right and bottom and left:
                    mapped_matrix[i][j] = 'TILE_POINT_UP_RIGHT_DOWN_LEFT'
                elif top and right and not bottom and not left:
                    mapped_matrix[i][j] = 'TILE_POINT_UP_RIGHT'
                elif top and left and not bottom and not right:
                    mapped_matrix[i][j] = 'TILE_POINT_UP_LEFT'
                elif bottom and right and not top and not left:
                    mapped_matrix[i][j] = 'TILE_POINT_DOWN_RIGHT'
                elif bottom and left and not top and not right:
                    mapped_matrix[i][j] = 'TILE_POINT_DOWN_LEFT'
                elif not bottom and left and not top and right:
                    mapped_matrix[i][j] = 'TILE_TOP'
                elif bottom and left and not top and right:
                    mapped_matrix[i][j] = 'TILE_TOP'
                else:
                    mapped_matrix[i][j] = 'TILE_CENTER'

            if matrix[i][j] == 2:
                mapped_matrix[i][j] = 'WATER_PORTAL'
            if matrix[i][j] == 3:
                mapped_matrix[i][j] = 'DIAMANTE_WATER'
            if matrix[i][j] == 4:
                mapped_matrix[i][j] = 'WATER_ANIMATION'
            if matrix[i][j] == 5:
                mapped_matrix[i][j] = 'PLAYER_WATER'
            
            if matrix[i][j] == 6:
                mapped_matrix[i][j] = 'FIRE_PORTAL'
            if matrix[i][j] == 7:
                mapped_matrix[i][j] = 'DIAMANTE_FIRE'
            if matrix[i][j] == 8:
                mapped_matrix[i][j] = 'FIRE_ANIMATION'
            if matrix[i][j] == 9:
                mapped_matrix[i][j] = 'PLAYER_FIRE'

    return mapped_matrix

from PIL import Image

# Open the image
def read_map_image(map_name):

    image = Image.open("./assets/maps/" + map_name)

    # Convert to RGB if not already
    image = image.convert("RGB")

    # Get the pixel data
    pixel_data = list(image.getdata())

    map_conversion_dict = {
        (255, 255, 255): 0, # Empty
        (0, 0, 0): 1, # Tile

        (0, 188, 212): 2, # portal agua
        (3, 169, 244): 3, # diamante agua
        (33, 150, 243): 4, # danger agua
        (63, 81, 181): 5, # player agua

        (255, 235, 59): 6, # portal fogo
        (255, 193, 7): 7, # diamante fogo
        (255, 152, 0): 8, # danger fogo
        (255, 87, 34): 9, # player fogo

    }

    # Convert to a 2D list (list of lists)
    width, height = image.size
    list_of_lists = [[map_conversion_dict[data] for data in pixel_data[i * width:(i + 1) * width]] for i in range(height)]

    return map_tiles(list_of_lists)

MAPS = {
    1: read_map_image("mapa3.png"), 
    2: read_map_image("mapa2.png"),
    # 3: MAP3,
    # 4: MAP4,
    # 5: MAP5
}